import { CropInfo, MarketPriceItem, WeatherDay, CropDisease, InputItem } from './types';

export const CROPS_DATA: CropInfo[] = [
  {
    id: 'rice',
    name: 'ধান',
    nameEn: 'Rice (Paddy)',
    scientificName: 'Oryza sativa',
    category: 'দানা ফসল',
    categoryEn: 'Cereal Grain',
    seasonTag: 'আউশ, আমন ও বোরো',
    seasonTagEn: 'Aus, Aman & Boro',
    image: '/src/rice.jpg',
    suitableSeason: 'আউশ: ১ এপ্রিল - ৩০ এপ্রিল | আমন: ১৫ জুলাই - ১৫ আগস্ট | বোরো: ১৫ ডিসেম্বর - ৩১ জানুয়ারি',
    suitableSeasonEn: 'Aus: 1 Apr - 30 Apr | Aman: 15 Jul - 15 Aug | Boro: 15 Dec - 31 Jan',
    soilType: 'দোআঁশ ও এঁটেল দোআঁশ মাটি উপযুক্ত। জমিতে ভালো পানি নিষ্কাশন ব্যবস্থা থাকা দরকার।',
    soilTypeEn: 'Loamy and clay-loam soils are ideal. Requires reliable drainage and retention.',
    seedRate: 'প্রতি একরে ৭-৮ কেজি সুস্থ ও রোগমুক্ত বীজ।',
    seedRateEn: '7-8 kg certified healthy seeds per acre.',
    fertilizerGuide: 'ইউরিয়া, টিএসপি, ডিএপি, এমওপি এবং জিপসাম সার সুষম মাত্রায় প্রয়োগ করুন। অতিরিক্ত ইউরিয়া পরিহার করুন।',
    fertilizerGuideEn: 'Apply balanced Urea, TSP, DAP, MOP, and Gypsum. Avoid excessive urea application.',
    irrigationGuide: 'জমিতে প্রয়োজন অনুযায়ী ২-৩ ইঞ্চি পানি রাখুন। অতিরিক্ত পানি দীর্ঘ সময় জমিয়ে রাখবেন না। ধান পাকার ৭-১০ দিন আগে পানি বের করে দিন।',
    irrigationGuideEn: 'Maintain 2-3 inches of standing water. Drain water 7-10 days before harvest.',
    commonPests: ['মাজরা পোকা', 'বাদামি গাছফড়িং (BPH)', 'পাতা মোড়ানো পোকা', 'গলমাছি'],
    commonPestsEn: ['Stem Borer', 'Brown Planthopper (BPH)', 'Leaf Folder', 'Gall Midge'],
    commonDiseases: ['ধান ব্লাস্ট', 'ব্যাকটেরিয়াল লিফ ব্লাইট', 'শীথ ব্লাইট', 'বাদামি দাগ রোগ'],
    commonDiseasesEn: ['Rice Blast', 'Bacterial Leaf Blight (BLB)', 'Sheath Blight', 'Brown Spot'],
    harvestingTime: 'শীষের প্রায় ৮০-৮৫% ধান পেকে সোনালী বা হলুদ হলে কাটাই উপযুক্ত।',
    harvestingTimeEn: 'Harvest when 80-85% of grains in panicles turn golden-yellow.',
    preservation: 'ধান ভালোভাবে রোদে শুকিয়ে ১২% আর্দ্রতায় এনে শুকনা ও পরিষ্কার স্থানে বায়ুরোধী পাত্রে সংরক্ষণ করুন।',
    preservationEn: 'Sun-dry to 12% moisture level and store in clean airtight containers in a cool, dry place.',
  },
  {
    id: 'wheat',
    name: 'গম',
    nameEn: 'Wheat',
    scientificName: 'Triticum aestivum',
    category: 'দানা ফসল',
    categoryEn: 'Cereal Grain',
    seasonTag: 'রবি মৌসুম (শীতকাল)',
    seasonTagEn: 'Rabi Season (Winter)',
    image: '/src/wheat.jpg',
    suitableSeason: '১৫ নভেম্বর - ৩০ নভেম্বর (রবি মৌসুম)',
    suitableSeasonEn: '15 November - 30 November (Rabi season)',
    soilType: 'উর্বর দোআঁশ ও বেলে-দোআঁশ মাটি গম চাষের জন্য সবচেয়ে ভালো।',
    soilTypeEn: 'Fertile loam and sandy-loam soils with good drainage.',
    seedRate: 'প্রতি একরে ৪৮-৫০ কেজি বীজ।',
    seedRateEn: '48-50 kg seeds per acre.',
    fertilizerGuide: 'ইউরিয়া, টিএসপি, এমওপি, জিপসাম এবং বোরন সার নির্দেশিত মাত্রায় প্রয়োগ করুন।',
    fertilizerGuideEn: 'Apply recommended amounts of Urea, TSP, MOP, Gypsum, and Boron.',
    irrigationGuide: 'সাধারণত ৩টি সেচ প্রয়োজন: প্রথম সেচ মুকুট শিকড় গজানোর সময় (১৭-২১ দিন), দ্বিতীয় সেচ শীষ বের হওয়ার মুখে (৪৫-৫০ দিন), তৃতীয় সেচ দানা গঠনের সময় (৭০-৭৫ দিন)।',
    irrigationGuideEn: '3 irrigations recommended: Crown root stage (17-21 days), heading stage (45-50 days), grain filling stage (70-75 days).',
    commonPests: ['জাব পোকা', 'ইঁদুর'],
    commonPestsEn: ['Aphids', 'Field Rodents'],
    commonDiseases: ['গমের ব্লাস্ট', 'পাতার মরিচা রোগ', 'আলগা চিটা'],
    commonDiseasesEn: ['Wheat Blast', 'Leaf Rust', 'Loose Smut'],
    harvestingTime: 'গাছ ও শীষ সম্পূর্ণ হলুদ হয়ে শুকিয়ে গেলে সকালে গম কাটা উচিত।',
    harvestingTimeEn: 'Harvest in the morning when plants and spikes turn fully straw-golden.',
    preservation: 'রোদে শুকিয়ে আর্দ্রতা ১০-১২% এ এনে ঠান্ডা স্থানে সংরক্ষণ করুন।',
    preservationEn: 'Sun-dry down to 10-12% moisture and store in dry sealed containers.',
  },
  {
    id: 'maize',
    name: 'ভুট্টা',
    nameEn: 'Maize (Corn)',
    scientificName: 'Zea mays',
    category: 'দানা ফসল',
    categoryEn: 'Cereal Grain',
    seasonTag: 'রবি ও খরিফ মৌসুম',
    seasonTagEn: 'Rabi & Kharif Season',
    image: '/src/maize.jpg',
    suitableSeason: 'রবি মৌসুম: অক্টোবর - নভেম্বর | খরিফ মৌসুম: ফেব্রুয়ারি - মার্চ',
    suitableSeasonEn: 'Rabi: October - November | Kharif: February - March',
    soilType: 'পানি জমে না এমন গভীর উর্বর বেলে-দোআঁশ ও দোআঁশ মাটি।',
    soilTypeEn: 'Deep fertile sandy-loam or loamy soils with no waterlogging.',
    seedRate: 'প্রতি একরে ৮-১০ কেজি হাইব্রিড ভুট্টা বীজ।',
    seedRateEn: '8-10 kg hybrid maize seed per acre.',
    fertilizerGuide: 'ভুট্টায় প্রচুর খাদ্য উপাদান প্রয়োজন। ইউরিয়া, টিএসপি, পটাশ, জিপসাম এবং জিংক সালফেট প্রয়োগ আবশ্যক।',
    fertilizerGuideEn: 'Heavy nutrient feeder: Apply Urea, TSP, MOP, Gypsum, and Zinc Sulphate in splits.',
    irrigationGuide: 'গাছের ৪-৫ পাতা বয়সে প্রথম সেচ, ৮-১০ পাতা বয়সে দ্বিতীয় সেচ, ফুল আসার সময় তৃতীয় সেচ ও দানা পুষ্ট হওয়ার সময় চতুর্থ সেচ দিন।',
    irrigationGuideEn: 'Irrigate at 4-5 leaf stage, 8-10 leaf stage, tasseling/silking, and grain milky stage.',
    commonPests: ['ফল আর্মিওয়ার্ম', 'কাণ্ড ছিদ্রকারী পোকা'],
    commonPestsEn: ['Fall Armyworm', 'Stem Borer'],
    commonDiseases: ['পাতার দাগ রোগ', 'কাণ্ড পচা রোগ', 'বীজ পচা রোগ'],
    commonDiseasesEn: ['Leaf Blight (Turcicum)', 'Stalk / Stem Rot', 'Seedling Rot'],
    harvestingTime: 'মোচার খোসা শুকিয়ে খড়ের রঙ ধারণ করলে এবং দানার গোড়ায় কালো দাগ দেখা দিলে সংগ্রহ করুন।',
    harvestingTimeEn: 'Harvest when husks turn straw-dry and a black layer forms at the grain base.',
    preservation: 'দানা ছাড়িয়ে ১২% আর্দ্রতায় শুকিয়ে সংরক্ষণ করুন।',
    preservationEn: 'Shell grains, dry thoroughly to 12% moisture, and store air-tight.',
  },
  {
    id: 'potato',
    name: 'আলু',
    nameEn: 'Potato',
    scientificName: 'Solanum tuberosum',
    category: 'সবজি',
    categoryEn: 'Vegetable',
    seasonTag: 'শীতকালীন প্রধান ফসল',
    seasonTagEn: 'Prime Winter Crop',
    image: '/src/potato.jpg',
    suitableSeason: '১ নভেম্বর - ২০ নভেম্বর (রবি মৌসুম)',
    suitableSeasonEn: '1 November - 20 November (Rabi season)',
    soilType: 'হালকা বেলে দোআঁশ ও উর্বর পলি দোআঁশ মাটি আলু চাষের জন্য আদর্শ।',
    soilTypeEn: 'Light sandy loam and fertile alluvial loam soils rich in organic matter.',
    seedRate: 'প্রতি একরে ৬০০-৮০০ কেজি প্রত্যয়িত বীজ আলু।',
    seedRateEn: '600-800 kg certified seed tubers per acre.',
    fertilizerGuide: 'জৈব সারসহ ইউরিয়া, টিএসপি, পটাশ ও ম্যাগনেসিয়াম প্রয়োজন। মাটির নিচে কন্দ বৃদ্ধিতে পটাশের ভূমিকা গুরুত্বপূর্ণ।',
    fertilizerGuideEn: 'Apply organic manure, Urea, TSP, Potash, and Magnesium. Potash is crucial for tuber bulking.',
    irrigationGuide: 'সাধারণত ২-৩টি হালকা সেচ লাগে। আলুর গোড়ায় যেন পানি দীর্ঘক্ষণ জমে না থাকে।',
    irrigationGuideEn: 'Provide 2-3 light furrows; avoid standing water on tuber ridges.',
    commonPests: ['আলুর জাব পোকা', 'কাটুই পোকা'],
    commonPestsEn: ['Aphids (vectors of viruses)', 'Cutworms'],
    commonDiseases: ['নাবী ধসা (Late Blight)', 'আগাম ধসা (Early Blight)', 'কালো পা রোগ'],
    commonDiseasesEn: ['Late Blight (Phytophthora)', 'Early Blight', 'Blackleg / Soft Rot'],
    harvestingTime: 'রোপণের ৮০-৯০ দিন পর গাছ শুকিয়ে গেলে আলু তুলতে হয়।',
    harvestingTimeEn: 'Harvest 80-90 days after sowing when foliage naturally withers.',
    preservation: 'হিমাগারে বা শুষ্ক ঠান্ডা অন্ধকার স্থানে বাতাস চলাচলযুক্ত অবস্থায় সংরক্ষণ।',
    preservationEn: 'Cold storage (3-4°C) or well-ventilated dark, dry rustic racks.',
  },
  {
    id: 'mustard',
    name: 'সরিষা',
    nameEn: 'Mustard',
    scientificName: 'Brassica napus',
    category: 'তৈলবীজ ও মসলা',
    categoryEn: 'Oilseed & Spice',
    seasonTag: 'স্বল্পমেয়াদী রবি ফসল',
    seasonTagEn: 'Short-duration Rabi Crop',
    image: '/src/mustard.jpg',
    suitableSeason: 'অক্টোবরের শেষ থেকে নভেম্বরের মাঝামাঝি',
    suitableSeasonEn: 'Late October to mid-November',
    soilType: 'উর্বর দোআঁশ ও পলি-দোআঁশ মাটি।',
    soilTypeEn: 'Fertile loamy and silt-loam soils.',
    seedRate: 'প্রতি একরে ৩-৩.৫ কেজি সুস্থ বীজ।',
    seedRateEn: '3-3.5 kg certified seeds per acre.',
    fertilizerGuide: 'ইউরিয়া, টিএসপি, পটাশ ও সালফার (গন্ধক) সার সরিষার তেলের পরিমাণ বাড়ায়।',
    fertilizerGuideEn: 'Urea, TSP, Potash, and Sulphur (Sulphur significantly increases oil content).',
    irrigationGuide: 'ফুল আসার আগে একবার (২০-২৫ দিন) এবং শুঁটি গঠনের সময় একবার (৪০-৪৫ দিন) হালকা সেচ।',
    irrigationGuideEn: 'Light irrigation at pre-flowering (20-25 days) and pod formation (40-45 days).',
    commonPests: ['জাব পোকা (সবচেয়ে ক্ষতিকর)', 'শুঁটি ছিদ্রকারী পোকা'],
    commonPestsEn: ['Mustard Aphids (Lipaphis erysimi)', 'Pod Borers'],
    commonDiseases: ['অল্টারনারিয়া ব্লাইট', 'ডাউনি মিলডিউ'],
    commonDiseasesEn: ['Alternaria Blight', 'Downy Mildew / White Rust'],
    harvestingTime: 'গাছ ও শুঁটি ৭০-৮০% হলুদ হলে সকালে কাটা উচিত।',
    harvestingTimeEn: 'Harvest in the morning when 70-80% of pods turn straw yellow.',
    preservation: 'রোদে শুকিয়ে আর্দ্রতা ৮-৯% এ এনে বায়ুরোধী পাত্রে রাখা।',
    preservationEn: 'Dry under the sun to 8-9% moisture and keep in sealed polythene bags.',
  },
  {
    id: 'tomato',
    name: 'টমেটো',
    nameEn: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    category: 'সবজি',
    categoryEn: 'Vegetable',
    seasonTag: 'শীত ও গ্রীষ্মকালীন',
    seasonTagEn: 'Winter & Summer',
    image: '/src/tomato.jpg',
    suitableSeason: 'শীতকালীন: অক্টোবর - নভেম্বর | গ্রীষ্মকালীন আগাম: মে - জুলাই (বারি হাইব্রিড-৮)',
    suitableSeasonEn: 'Winter: October - November | Summer early: May - July (BARI Hybrid-8)',
    soilType: 'উর্বর বেলে দোআঁশ ও পলি দোআঁশ মাটি। পিএইচ (pH) ৬.০-৭.০ ও পর্যাপ্ত জৈব পদার্থ দরকার।',
    soilTypeEn: 'Fertile sandy-loam and alluvial loam with pH 6.0-7.0 and rich organic matter.',
    seedRate: 'প্রতি একরে ৮০-১০০ গ্রাম হাইব্রিড বীজ (চারা বানিয়ে ২৫-৩০ দিন বয়সে জমিতে রোপণ)।',
    seedRateEn: '80-100 g hybrid seed per acre (transplant 25-30 day seedlings).',
    fertilizerGuide: 'প্রতি একরে ৪-৫ টন গোবর, ১০০ কেজি ইউরিয়া, ১৫০ কেজি টিএসপি, ১০০ কেজি এমওপি এবং ২০ কেজি জিপসাম। ফুল ও ফল ধরার পর ইউরিয়া ও পটাশ উপরি প্রয়োগ করুন।',
    fertilizerGuideEn: '4-5 tons cowdung, 100 kg Urea, 150 kg TSP, 100 kg MOP, and 20 kg Gypsum per acre. Topdress after fruit set.',
    irrigationGuide: 'টমেটো খরা ও অতিরিক্ত পানি উভয়তেই সংবেদনশীল। প্রতি ৭-১০ দিন পর পর হালকা সেচ দিন। গোড়ায় নালা দিয়ে পানি দেওয়া উত্তম।',
    irrigationGuideEn: 'Sensitive to both drought and waterlogging. Irrigate every 7-10 days via furrows.',
    commonPests: ['সাদা মাছি (Whitefly)', 'টমেটোর ফল ছিদ্রকারী পোকা', 'জাব পোকা', 'পাতা সুড়ঙ্গকারী পোকা'],
    commonPestsEn: ['Whiteflies', 'Tomato Fruit Borer (Helicoverpa)', 'Aphids', 'Leaf Miners'],
    commonDiseases: ['নাবী ধসা (Late Blight)', 'পাতা কোঁকড়ানো ভাইরাস (Leaf Curl Virus)', 'আগাম ধসা', 'ব্যাকটেরিয়াল ঢলে পড়া'],
    commonDiseasesEn: ['Late Blight', 'Tomato Leaf Curl Virus (TYLCV)', 'Early Blight', 'Bacterial Wilt'],
    harvestingTime: 'চারা রোপণের ৬০-৮০ দিন পর ফল সংগ্রহ শুরু হয়। বাজারের দূরত্ব অনুযায়ী আধা-পাকা বা পূর্ণ পাকা ফল তুলুন।',
    harvestingTimeEn: 'Harvest starts 60-80 days after transplanting at breaker or red-ripe stage.',
    preservation: 'পাকা টমেটো ঠান্ডা ও ছায়াযুক্ত স্থানে ১০-১২° সে. তাপমাত্রায় ৮-১০ দিন পর্যন্ত তাজা থাকে।',
    preservationEn: 'Store at 10-12°C in a cool ventilated place for 8-10 days.',
  },
  {
    id: 'brinjal',
    name: 'বেগুন',
    nameEn: 'Brinjal (Eggplant)',
    scientificName: 'Solanum melongena',
    category: 'সবজি',
    categoryEn: 'Vegetable',
    seasonTag: 'বারোমাসি সবজি',
    seasonTagEn: 'Perennial / All-Season',
    image: '/src/brinjal.jpg',
    suitableSeason: 'শীতকালীন: আগস্ট - অক্টোবর | বারোমাসি ও গ্রীষ্মকালীন: ফেব্রুয়ারি - মে',
    suitableSeasonEn: 'Winter: August - October | Year-round / Summer: February - May',
    soilType: 'পানি জমে না এমন সুনিষ্কাশিত গভীর দোআঁশ ও এঁটেল দোআঁশ মাটি সর্বোত্তম।',
    soilTypeEn: 'Well-drained deep loamy and clay-loam soils free of standing water.',
    seedRate: 'প্রতি একরে ১২০-১৫০ গ্রাম বীজ (চারা তৈরি করে ৩০-৩৫ দিন বয়সে নির্দিষ্ট দূরত্বে রোপণ)।',
    seedRateEn: '120-150 g seed per acre (transplant 30-35 day seedlings).',
    fertilizerGuide: 'জমি তৈরিতে গোবর ৫-৬ টন, ইউরিয়া ১০০ কেজি, টিএসপি ৮০ কেজি, এমওপি ৭০ কেজি, জিপসাম ২০ কেজি। ইউরিয়া ও পটাশ ৩ কিস্তিতে উপরি প্রয়োগ করুন।',
    fertilizerGuideEn: 'Cowdung 5-6 tons, 100 kg Urea, 80 kg TSP, 70 kg MOP, 20 kg Gypsum. Topdress Urea & Potash in 3 splits.',
    irrigationGuide: 'শীত মৌসুমে ১০-১৫ দিন পর পর সেচ দিন। গ্রীষ্মকালে মাটি শুকিয়ে এলে ৫-৭ দিন পর পর হালকা সেচ। গোড়ায় পানি জমতে দেওয়া যাবে না।',
    irrigationGuideEn: 'Irrigate every 10-15 days in winter, 5-7 days in dry summer. Keep bases well-aerated.',
    commonPests: ['ডগা ও ফল ছিদ্রকারী পোকা', 'সাদা মাছি', 'লাল মাকড়', 'জাব পোকা'],
    commonPestsEn: ['Shoot and Fruit Borer (Leucinodes)', 'Whiteflies', 'Red Spider Mites', 'Aphids'],
    commonDiseases: ['ব্যাকটেরিয়াল ঢলে পড়া (Bacterial Wilt)', 'ফোমোপসিস ব্লাইট ও ফল পচা', 'গোড়া পচা রোগ', 'লিটল লিফ ভাইরাস'],
    commonDiseasesEn: ['Bacterial Wilt (Ralstonia)', 'Phomopsis Blight & Fruit Rot', 'Damping Off / Root Rot', 'Little Leaf Virus'],
    harvestingTime: 'চারা রোপণের ৬০-৭০ দিন পর বেগুন ধরা শুরু হয়। কচি ও উজ্জ্বল চকচকে থাকা অবস্থায় নিয়মিত সংগ্রহ করুন।',
    harvestingTimeEn: 'Harvest starts 60-70 days after planting when fruits are tender and glossy.',
    preservation: 'শীতল ও শুষ্ক স্থানে বাতাস চলাচলযুক্ত ঝুড়িতে বেগুন ৪-৫ দিন সতেজ থাকে।',
    preservationEn: 'Keep in aerated baskets in cool dry conditions for 4-5 days.',
  },
  {
    id: 'cauliflower',
    name: 'ফুলকপি',
    nameEn: 'Cauliflower',
    scientificName: 'Brassica oleracea var. botrytis',
    category: 'সবজি',
    categoryEn: 'Vegetable',
    seasonTag: 'শীতকালীন ও আগাম জাত',
    seasonTagEn: 'Winter & Early Varieties',
    image: '/src/cauliflower.jpg',
    suitableSeason: 'আগাম জাত: আগস্ট - সেপ্টেম্বর | প্রধান মৌসুম: অক্টোবর - নভেম্বর | গ্রীষ্মকালীন জাত: মে - জুন',
    suitableSeasonEn: 'Early: August - September | Main: October - November | Summer: May - June',
    soilType: 'উর্বর ও পর্যাপ্ত জৈব সার সমৃদ্ধ দোআঁশ ও পলি দোআঁশ মাটি সবচেয়ে উপযোগী।',
    soilTypeEn: 'Fertile loam and silt-loam rich in organic compost.',
    seedRate: 'প্রতি একরে ১০০-১২০ গ্রাম উন্নত বীজ। ২৫-৩০ দিনের সুস্থ চারা সারি ৬০ সেমি ও চারা ৪৫ সেমি দূরত্বে রোপণ।',
    seedRateEn: '100-120 g improved seed per acre. Transplant 25-30 day seedlings at 60cm x 45cm spacing.',
    fertilizerGuide: 'প্রতি একরে ৪-৫ টন গোবর, ১০০ কেজি ইউরিয়া, ৮০ কেজি টিএসপি, ৮০ কেজি এমওপি এবং ৫ কেজি বোরাক্স সার অপরিহার্য (বোরনের অভাবে বাদামি পচন হয়)।',
    fertilizerGuideEn: '4-5 tons compost, 100 kg Urea, 80 kg TSP, 80 kg MOP, and 5 kg Borax (essential to prevent brown curds).',
    irrigationGuide: 'মাটিতে রসের অভাব হলে ফুল ছোট ও আঁটসাঁটহীন হয়। রোপণের পর হালকা সেচ দিন এবং এরপর ৮-১০ দিন পর পর পরিমিত সেচ দিন।',
    irrigationGuideEn: 'Moisture stress yields loose, discolored curds. Irrigate lightly every 8-10 days.',
    commonPests: ['ফুলকপির লেদা পোকা (Prodenia)', 'হীরা পিঠ মথ (DBM)', 'জাব পোকা'],
    commonPestsEn: ['Tobacco Caterpillar (Spodoptera)', 'Diamondback Moth (DBM)', 'Cabbage Aphids'],
    commonDiseases: ['অল্টারনারিয়া ব্লাইট (পাতার দাগ)', 'কালো পচা (Black rot)', 'হুইপটেল রোগ', 'বাদামি পচন (Brown rot)'],
    commonDiseasesEn: ['Alternaria Leaf Spot', 'Black Rot (Xanthomonas)', 'Whiptail (Mo deficiency)', 'Brown Curd Rot (Boron deficiency)'],
    harvestingTime: 'চারা রোপণের ৬০-৭৫ দিন পর ফুল নিরেট ও উজ্জ্বল সাদা থাকা অবস্থায় পাতা সহ কেটে তুলুন।',
    harvestingTimeEn: 'Harvest 60-75 days after transplanting when heads are compact and bright white.',
    preservation: 'ঠান্ডা ও আর্দ্র স্থানে সংরক্ষণ করলে ফুলকপি ৭-১০ দিন সতেজ থাকে।',
    preservationEn: 'Store in cool humid storage for 7-10 days.',
  },
  {
    id: 'papaya',
    name: 'পেঁপে',
    nameEn: 'Papaya',
    scientificName: 'Carica papaya',
    category: 'ফল ও অর্থকরী',
    categoryEn: 'Fruit & Cash Crop',
    seasonTag: 'বারোমাসি ফল ও পুষ্টিকর সবজি',
    seasonTagEn: 'Year-Round Fruit & Vegetable',
    image: '/src/papaya.jpg',
    suitableSeason: 'বছরের যেকোনো সময়ে রোপণ সম্ভব; তবে সেপ্টেম্বর-অক্টোবর এবং ফেব্রুয়ারি-মার্চ চারা রোপণের শ্রেষ্ঠ সময়।',
    suitableSeasonEn: 'Plant year-round; September-October and February-March are best.',
    soilType: 'উঁচু ও মাঝারি উঁচু বেলে-দোআঁশ মাটি। পেঁপে গাছ জলাবদ্ধতা একদম সহ্য করতে পারে না, ড্রেন অপরিহার্য।',
    soilTypeEn: 'High or medium upland sandy loam. Zero tolerance for waterlogging; high drainage ditches mandatory.',
    seedRate: 'প্রতি একরে ২০০-২৫০ গ্রাম বীজ (অথবা প্রায় ১,০০০-১,২০০টি সুস্থ পলিব্যাগ চারা)।',
    seedRateEn: '200-250 g seed or 1,000-1,200 healthy polybag seedlings per acre.',
    fertilizerGuide: 'প্রতিটি গর্তে ১০ কেজি পচা গোবর, ৫০০ গ্রাম টিএসপি, ৫০০ গ্রাম পটাশ, ২৫০ গ্রাম জিপসাম ও ৫০ গ্রাম বোরন সার। প্রতি ২ মাস পর পর ইউরিয়া ও পটাশ উপরি দিন।',
    fertilizerGuideEn: 'Pit mix: 10 kg compost, 500g TSP, 500g Potash, 250g Gypsum, 50g Boron. Topdress Urea & Potash every 2 months.',
    irrigationGuide: 'শুষ্ক মৌসুমে প্রতি ৭-১০ দিন পর পর নালার মাধ্যমে সেচ দিন। বর্ষাকালে গাছের গোড়ায় পানি জমলে দ্রুত নিষ্কাশন করুন।',
    irrigationGuideEn: 'Irrigate via ring furrows every 7-10 days in dry periods. Drain completely during monsoon.',
    commonPests: ['মিলিবাগ (দই পোকা)', 'সাদা মাছি', 'মাকড় (Mites)'],
    commonPestsEn: ['Mealybugs', 'Whiteflies', 'Spider Mites'],
    commonDiseases: ['পেঁপের রিং স্পট ভাইরাস (PRSV)', 'গোড়া ও শিকড় পচা রোগ (Foot rot)', 'অ্যানথ্রাকনোজ (ফল পচা)'],
    commonDiseasesEn: ['Papaya Ringspot Virus (PRSV)', 'Foot / Stem Rot (Pythium)', 'Anthracnose Fruit Rot'],
    harvestingTime: 'চারা লাগানোর ৩-৪ মাস পর থেকে কাঁচা সবজি পেঁপে এবং ৯-১০ মাস পর থেকে পাকা ফল সংগ্রহ করা যায়।',
    harvestingTimeEn: 'Green vegetable harvest at 3-4 months; ripe sweet fruit from 9-10 months.',
    preservation: 'কাঁচা পেঁপে স্বাভাবিক তাপমাত্রায় ১০-১২ দিন এবং পাকা পেঁপে ঠান্ডা স্থানে ৫-৭ দিন রাখা যায়।',
    preservationEn: 'Green papaya stores 10-12 days at room temperature; ripe fruit 5-7 days in cool storage.',
  },
  {
    id: 'banana',
    name: 'কলা',
    nameEn: 'Banana',
    scientificName: 'Musa acuminata',
    category: 'ফল ও অর্থকরী',
    categoryEn: 'Fruit & Cash Crop',
    seasonTag: 'বারোমাসি অর্থকরী ফল',
    seasonTagEn: 'High-Value Commercial Crop',
    image: '/src/banana.jpg',
    suitableSeason: 'বছরে তিন মৌসুমে চারা লাগানো যায়: আশ্বিন-কার্তিক (অক্টোবর-নভেম্বর), মাঘ-ফাল্গুন (ফেব্রুয়ারি-মার্চ) ও জ্যৈষ্ঠ-আষাঢ় (মে-জুন)।',
    suitableSeasonEn: 'Plant in October-November, February-March, or May-June.',
    soilType: 'উর্বর, গভীর, সুনিষ্কাশিত পলল দোআঁশ ও এঁটেল দোআঁশ মাটি কলা চাষের জন্য সেরা।',
    soilTypeEn: 'Deep fertile alluvial loam and clay loam with abundant organic content.',
    seedRate: 'প্রতি একরে সুস্থ তলোয়ার সাকার (Sword sucker) প্রায় ১,২০০-১,৪০০টি (২ মি. x ২ মি. দূরত্বে)।',
    seedRateEn: '1,200-1,400 disease-free sword suckers per acre spaced 2m x 2m.',
    fertilizerGuide: 'প্রতি গাছে ১৫-২০ কেজি পচা গোবর, ৫০০ গ্রাম ইউরিয়া, ৪০০ গ্রাম টিএসপি, ৬০০ গ্রাম এমওপি এবং ১০০ গ্রাম জিপসাম। সার ৪-৫ কিস্তিতে উপরি প্রয়োগ করুন।',
    fertilizerGuideEn: 'Per plant: 15-20 kg compost, 500g Urea, 400g TSP, 600g MOP, 100g Gypsum in 4-5 split applications.',
    irrigationGuide: 'কলা গাছে প্রচুর পানি প্রয়োজন। খরা মৌসুমে ১০-১২ দিন পর পর সেচ দিন এবং বৃষ্টির পানি নিষ্কাশনে গভীর নালা রাখুন।',
    irrigationGuideEn: 'High water requirement. Irrigate every 10-12 days during dry spells; provide deep drains for monsoons.',
    commonPests: ['কলা গাছের পাতা ও ফল বিটল পোকা', 'কলার কন্দ উইভিল', 'থ্রিপস পোকা'],
    commonPestsEn: ['Banana Beetle', 'Banana Corm Weevil', 'Rust Thrips'],
    commonDiseases: ['সিগাটোকা রোগ (Black / Yellow Sigatoka)', 'পানামা রোগ (Fusarium wilt)', 'গুচ্ছ মাথা ভাইরাস (Bunchy top)'],
    commonDiseasesEn: ['Black / Yellow Sigatoka', 'Panama Wilt (Fusarium)', 'Banana Bunchy Top Virus (BBTV)'],
    harvestingTime: 'চারা লাগানোর ১১-১৩ মাস পর মোচা থেকে কলা পুষ্ট হয়। কলার খাঁজগুলো গোলাকার রূপ নিলে কাঁদি কাটুন।',
    harvestingTimeEn: 'Harvest 11-13 months after planting when banana fingers become rounded and ridges soften.',
    preservation: 'ছায়াযুক্ত ঠান্ডা ও বাতাসযুক্ত স্থানে কাঁদি ঝুলিয়ে রাখলে কলা প্রাকৃতিকভাবে সুন্দর পাকে।',
    preservationEn: 'Hang bunches in cool, ventilated shaded sheds for natural, even ripening.',
  },
  {
    id: 'betel',
    name: 'পান',
    nameEn: 'Betel Leaf',
    scientificName: 'Piper betle',
    category: 'ফল ও অর্থকরী',
    categoryEn: 'Fruit & Cash Crop',
    seasonTag: 'বারোমাসি অর্থকরী বরোজ',
    seasonTagEn: 'Commercial Baroj Vine',
    image: '/src/betel.jpg',
    suitableSeason: 'বছরের যেকোনো সময় তবে মে-জুলাই মাস বরোজ তৈরির জন্য সেরা।',
    suitableSeasonEn: 'Planting can occur year-round; May to July is optimal for preparing baroj.',
    soilType: 'উঁচু ও মাঝারি উঁচু ছায়াযুক্ত বেলে-দোআঁশ মাটি। জল নিষ্কাশন অত্যন্ত জরুরি।',
    soilTypeEn: 'High, well-drained shaded sandy-loam soils with absolute drainage.',
    seedRate: 'প্রতি বরোজে প্রায় ১০,০০০-১২,০০০ লতা কাটিং।',
    seedRateEn: 'Approximately 10,000-12,000 vine cuttings per baroj.',
    fertilizerGuide: 'সরিষার খৈল, পচা গোবর ও অল্প মাত্রায় টিএসপি সার অত্যন্ত উপকারী।',
    fertilizerGuideEn: 'Mustard oil cake, decomposed compost, and moderate TSP applications are ideal.',
    irrigationGuide: 'বরোজে পর্যাপ্ত আর্দ্রতা রাখতে হালকা স্প্রিংকলার বা ঝাঝরি দিয়ে সেচ দিন। পানি জমতে দেওয়া যাবে না।',
    irrigationGuideEn: 'Maintain high micro-humidity using sprinkler rose cans; avoid any standing water.',
    commonPests: ['পানের সাদামাছি', 'থ্রিপস পোকা'],
    commonPestsEn: ['Betel Whitefly', 'Vine Thrips'],
    commonDiseases: ['গোড়া পচা (ফুট রট)', 'পাতা পোড়া রোগ'],
    commonDiseasesEn: ['Foot & Stem Rot (Phytophthora)', 'Leaf Spot / Anthracnose'],
    harvestingTime: 'রোপণের ৫-৬ মাস পর থেকে নিয়মিত পাতা সংগ্রহ করা যায়।',
    harvestingTimeEn: 'Regular leaf plucking begins 5-6 months after planting.',
    preservation: 'ভেজা ছালা বা কলাপাতা দিয়ে জড়িয়ে ঠান্ডা ঘরে পান তাজা রাখা হয়।',
    preservationEn: 'Wrap in moist jute sacks or banana leaves and store in cool cellars.',
  },
];

export const INITIAL_MARKET_PRICES: MarketPriceItem[] = [
  {
    id: '1',
    name: 'ধান',
    nameEn: 'Paddy Rice',
    category: 'ধান',
    categoryEn: 'Paddy',
    price: 1500,
    unit: 'টাকা/মণ',
    unitEn: 'BDT/maund (40kg)',
    location: 'ঢাকা',
    locationEn: 'Dhaka',
    change: 'up',
    changePercentage: 3.2,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ১০:০০',
    updatedAtEn: 'Today 10:00 AM',
  },
  {
    id: '2',
    name: 'আলু',
    nameEn: 'Potato',
    category: 'সবজি',
    categoryEn: 'Vegetable',
    price: 20,
    unit: 'টাকা/কেজি',
    unitEn: 'BDT/kg',
    location: 'ঢাকা',
    locationEn: 'Dhaka',
    change: 'down',
    changePercentage: 2.1,
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ১০:০০',
    updatedAtEn: 'Today 10:00 AM',
  },
  {
    id: '3',
    name: 'টমেটো',
    nameEn: 'Tomato',
    category: 'সবজি',
    categoryEn: 'Vegetable',
    price: 70,
    unit: 'টাকা/কেজি',
    unitEn: 'BDT/kg',
    location: 'ঢাকা',
    locationEn: 'Dhaka',
    change: 'up',
    changePercentage: 5.4,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ০৯:৩০',
    updatedAtEn: 'Today 09:30 AM',
  },
  {
    id: '4',
    name: 'আম',
    nameEn: 'Mango',
    category: 'ফল',
    categoryEn: 'Fruit',
    price: 40,
    unit: 'টাকা/কেজি',
    unitEn: 'BDT/kg',
    location: 'ঢাকা',
    locationEn: 'Dhaka',
    change: 'stable',
    changePercentage: 0,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ০৯:১৫',
    updatedAtEn: 'Today 09:15 AM',
  },
  {
    id: '5',
    name: 'গম',
    nameEn: 'Wheat',
    category: 'গম',
    categoryEn: 'Wheat',
    price: 1450,
    unit: 'টাকা/মণ',
    unitEn: 'BDT/maund (40kg)',
    location: 'ঢাকা',
    locationEn: 'Dhaka',
    change: 'up',
    changePercentage: 1.8,
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ০৮:৪৫',
    updatedAtEn: 'Today 08:45 AM',
  },
  {
    id: '6',
    name: 'মরিচ (কাঁচা)',
    nameEn: 'Green Chili',
    category: 'মসলা',
    categoryEn: 'Spices',
    price: 110,
    unit: 'টাকা/কেজি',
    unitEn: 'BDT/kg',
    location: 'ঢাকা',
    locationEn: 'Dhaka',
    change: 'down',
    changePercentage: 4.5,
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=300&auto=format&fit=crop&q=80',
    updatedAt: 'আজ সকাল ০৯:০০',
    updatedAtEn: 'Today 09:00 AM',
  },
];

export const INITIAL_WEATHER_DAYS: WeatherDay[] = [
  { dayName: 'আজ', date: '৪ সেপ্টেম্বর', temp: 32, condition: 'মেঘলা', humidity: 60, rainProbability: 80, warning: 'ভারী বৃষ্টির সম্ভাবনা' },
  { dayName: 'দিন ১', date: '৫ সেপ্টেম্বর', temp: 31, condition: 'বৃষ্টি', humidity: 65, rainProbability: 85, warning: 'ভারী বৃষ্টি সতর্কতা' },
  { dayName: 'দিন ২', date: '৬ সেপ্টেম্বর', temp: 30, condition: 'বৃষ্টি', humidity: 68, rainProbability: 80, warning: 'মাঝারি বৃষ্টি' },
  { dayName: 'দিন ৩', date: '৭ সেপ্টেম্বর', temp: 31, condition: 'হালকা বৃষ্টি', humidity: 62, rainProbability: 60 },
  { dayName: 'দিন ৪', date: '৮ সেপ্টেম্বর', temp: 32, condition: 'আংশিক মেঘলা', humidity: 58, rainProbability: 30 },
  { dayName: 'দিন ৫', date: '৯ সেপ্টেম্বর', temp: 33, condition: 'রৌদ্রোজ্জ্বল', humidity: 55, rainProbability: 15 },
  { dayName: 'দিন ৬', date: '১০ সেপ্টেম্বর', temp: 33, condition: 'রৌদ্রোজ্জ্বল', humidity: 52, rainProbability: 10 },
];

export const INITIAL_DISEASE: CropDisease = {
  id: 'rice-blast',
  crop: 'ধান',
  cropEn: 'Rice',
  name: 'ধানের ব্লাস্ট রোগ (Rice Blast)',
  nameEn: 'Rice Blast Disease (Magnaporthe oryzae)',
  description: 'ধানের ব্লাস্ট একটি ছত্রাকজনিত মারাত্মক রোগ। পাতা, গিঁট ও শীষে আক্রমণ করে এবং বেশি হলে ফলন উল্লেখযোগ্যভাবে কমে যেতে পারে।',
  descriptionEn: 'Rice blast is a serious fungal disease affecting leaves, nodes, and panicles, which can drastically reduce harvest yields.',
  symptoms: [
    'পাতায় চোখের মতো বাদামি দাগ দেখা যায়।',
    'দাগের মাঝখান ধূসর/সাদা হতে পারে।',
    'শীষের গিঁটে কালচে বা বাদামি দাগ হয়।',
    'আক্রান্ত শীষ শুকিয়ে যেতে পারে।',
    'বেশি আক্রমণে ধানের ফলন উল্লেখযোগ্যভাবে কমে যায়।',
  ],
  symptomsEn: [
    'Diamond or spindle-shaped brown spots with grey or whitish centers on leaves.',
    'Dark brown lesions at node junctions or panicle collar.',
    'Infected panicles turn white and fail to fill grains (neck blast).',
    'Drastic yield reduction under high humidity and excessive nitrogen.',
  ],
  organicSolution: 'আক্রান্ত অংশের পাতা কেটে পুড়িয়ে ফেলা। সকালে কাঠের ছাই গাছে ছিটানো এবং জমিতে সুষম জৈব সার প্রয়োগ।',
  organicSolutionEn: 'Remove and burn heavily infected leaves. Dust fresh wood ash in the early morning dew and maintain balanced organic fertilization.',
  chemicalSolution: {
    chemical: 'ট্রাইসাইক্লাজল 76% WP (Tricyclazole 76% WP)',
    usage: 'ধানের ব্লাস্ট রোগ নিয়ন্ত্রণে',
    usageEn: 'For control of Leaf, Node, and Neck Blast',
    dose: 'পণ্যের লেবেল অনুযায়ী অথবা স্থানীয় কৃষি কর্মকর্তার পরামর্শ অনুযায়ী প্রতি লিটার পানিতে ০.৭৫ গ্রাম মিশিয়ে বিকেলে স্প্রে করুন।',
    doseEn: 'Mix 0.75 g per liter of clean water and spray evenly in late afternoon.',
  },
  prevention: 'রোগমুক্ত প্রত্যয়িত বীজ শোধন করে বপন করুন। অতিরিক্ত ইউরিয়া সার পরিহার করে পরিমিত পটাশ ও সিলিকন সার ব্যবহার করুন।',
  preventionEn: 'Treat certified disease-free seeds before sowing. Avoid excessive nitrogen/urea, and ensure adequate Potash and Silicon nutrition.',
  image: 'https://images.unsplash.com/photo-1530507629858-e4977d30e9e0?w=600&auto=format&fit=crop&q=80',
};

export const INITIAL_INPUT_ITEMS: InputItem[] = [];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'n1',
    text: 'আজ আপনার এলাকায় ভারী বৃষ্টির সম্ভাবনা, ফসলের সুরক্ষার ব্যবস্থা নিন',
    textEn: 'Heavy rain expected in your area today; secure field drainage.',
    type: 'weather',
    unread: true,
  },
  {
    id: 'n2',
    text: 'আপনার জমিতে সেচ দেওয়ার উপযুক্ত সময় হয়েছে',
    textEn: 'Optimal time for light crop irrigation based on soil moisture.',
    type: 'task',
    unread: true,
  },
  {
    id: 'n3',
    text: 'ফসলের বর্তমান বৃদ্ধি অনুযায়ী সার প্রয়োগ করুন',
    textEn: 'Apply topdress fertilizer per crop growth stage guidelines.',
    type: 'task',
    unread: false,
  },
  {
    id: 'n4',
    text: 'আপনার এলাকায় রোগ বা পোকার আক্রমণের ঝুঁকি বেড়েছে',
    textEn: 'Elevated pest and disease warning in your district.',
    type: 'alert',
    unread: false,
  },
  {
    id: 'n5',
    text: 'আজকের বাজারে আপনার ফসলের দাম পরিবর্তন হয়েছে',
    textEn: 'Updated wholesale market prices available for your crops.',
    type: 'market',
    unread: false,
  },
  {
    id: 'n6',
    text: 'আজকের বিশেষ টিপস—সকালে বা বিকেলে সেচ দিলে পানির অপচয় কম হয়',
    textEn: 'Agronomy tip: Irrigate early morning or evening to minimize water evaporation.',
    type: 'tip',
    unread: false,
  },
];
